services:
    volleyball.controller.user:
        class: Volleyball\Bundle\UserBundle\Controller\UserController
        factory_service: sylius.controller.configuration_factory
        factory_method: createConfiguration
        arguments: ["sylius", "user", "VolleyballUserBundle:User"]
    volleyball.controller.admin:
        class: Volleyball\Bundle\UserBundle\Controller\AdminController
        factory_service: sylius.controller.configuration_factory
        factory_method: createConfiguration
        arguments: ["sylius", "admin", "VolleyballUserBundle:Admin"]